language: generic

os: linux

addons:
  apt:
    update: true

jobs:
  include:
    - name: "Docker and Integration Tests"
      os: linux
      dist: jammy
      services:
        - docker
      env:
        - TAG=`if [ $TRAVIS_BRANCH == "master" ]; then echo -n latest; else echo -n $TRAVIS_BRANCH; fi`
        - REST_TAG=$TAG
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build . -t $TRAVIS_REPO_SLUG:$TAG
      after_success:
        - |
          if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            docker push $TRAVIS_REPO_SLUG:$TAG
          fi